// AI Provider configurations with 79 providers including z.ai and opencode
// API keys are NEVER exposed to client - all requests go through secure API routes

export interface AIProvider {
  id: string;
  name: string;
  icon: string;
  category: string;
  models: string[];
  defaultModel: string;
  keyPlaceholder: string;
  docs: string;
  supportsVision?: boolean;
  supportsAudio?: boolean;
  local?: boolean;
}

export const AI_PROVIDERS: Record<string, AIProvider> = {
  // ===== Z.AI & OPENCODE =====
  'zai': {
    id: 'zai',
    name: 'Z.ai',
    icon: '🤖',
    category: 'Featured',
    models: ['glm-4-plus', 'glm-4', 'glm-4-flash', 'glm-4-air', 'glm-4-long', 'glm-4v-plus', 'glm-4v'],
    defaultModel: 'glm-4-plus',
    keyPlaceholder: 'Z.ai API Key',
    docs: 'https://open.bigmodel.cn/',
    supportsVision: true,
  },
  'opencode': {
    id: 'opencode',
    name: 'OpenCode',
    icon: '💻',
    category: 'Featured',
    models: ['opencode-7b', 'opencode-13b', 'opencode-34b', 'opencode-coder'],
    defaultModel: 'opencode-13b',
    keyPlaceholder: 'OpenCode API Key',
    docs: 'https://opencode.ai/',
    supportsVision: false,
  },

  // ===== MAJOR CLOUD PROVIDERS =====
  'openai': {
    id: 'openai',
    name: 'OpenAI',
    icon: '🟢',
    category: 'Major Cloud',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-4', 'gpt-3.5-turbo', 'o1', 'o1-mini', 'o1-preview'],
    defaultModel: 'gpt-4o',
    keyPlaceholder: 'sk-...',
    docs: 'https://platform.openai.com/api-keys',
    supportsVision: true,
    supportsAudio: true,
  },
  'anthropic': {
    id: 'anthropic',
    name: 'Anthropic',
    icon: '🟣',
    category: 'Major Cloud',
    models: ['claude-3-5-sonnet-20241022', 'claude-3-5-haiku-20241022', 'claude-3-opus-20240229'],
    defaultModel: 'claude-3-5-sonnet-20241022',
    keyPlaceholder: 'sk-ant-...',
    docs: 'https://console.anthropic.com/',
    supportsVision: true,
  },
  'google': {
    id: 'google',
    name: 'Google AI',
    icon: '🔵',
    category: 'Major Cloud',
    models: ['gemini-2.0-flash-exp', 'gemini-1.5-pro', 'gemini-1.5-flash', 'gemini-pro'],
    defaultModel: 'gemini-2.0-flash-exp',
    keyPlaceholder: 'AIza...',
    docs: 'https://aistudio.google.com/',
    supportsVision: true,
    supportsAudio: true,
  },

  // ===== CHINESE AI PROVIDERS =====
  'deepseek': {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: '🔮',
    category: 'Chinese AI',
    models: ['deepseek-chat', 'deepseek-coder', 'deepseek-reasoner'],
    defaultModel: 'deepseek-chat',
    keyPlaceholder: 'sk-...',
    docs: 'https://platform.deepseek.com/',
  },
  'moonshot': {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    icon: '🌙',
    category: 'Chinese AI',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
    defaultModel: 'moonshot-v1-8k',
    keyPlaceholder: 'sk-...',
    docs: 'https://platform.moonshot.cn/',
  },
  'zhipu': {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    icon: '💎',
    category: 'Chinese AI',
    models: ['glm-4', 'glm-4-flash', 'glm-4-plus', 'glm-4-long'],
    defaultModel: 'glm-4',
    keyPlaceholder: 'API Key',
    docs: 'https://open.bigmodel.cn/',
  },
  'qwen': {
    id: 'qwen',
    name: 'Alibaba Qwen',
    icon: '🔷',
    category: 'Chinese AI',
    models: ['qwen-turbo', 'qwen-plus', 'qwen-max', 'qwen-max-longcontext'],
    defaultModel: 'qwen-max',
    keyPlaceholder: 'sk-...',
    docs: 'https://dashscope.console.aliyun.com/',
  },
  'baichuan': {
    id: 'baichuan',
    name: 'Baichuan AI',
    icon: '🌊',
    category: 'Chinese AI',
    models: ['Baichuan4', 'Baichuan3-Turbo', 'Baichuan3-Turbo-128k'],
    defaultModel: 'Baichuan4',
    keyPlaceholder: 'API Key',
    docs: 'https://platform.baichuan-ai.com/',
  },
  'minimax': {
    id: 'minimax',
    name: 'MiniMax',
    icon: '⚡',
    category: 'Chinese AI',
    models: ['abab6.5-chat', 'abab6.5s-chat', 'abab5.5-chat'],
    defaultModel: 'abab6.5-chat',
    keyPlaceholder: 'API Key',
    docs: 'https://api.minimax.chat/',
  },
  'siliconflow': {
    id: 'siliconflow',
    name: 'SiliconFlow',
    icon: '💠',
    category: 'Chinese AI',
    models: ['deepseek-ai/DeepSeek-V3', 'Qwen/Qwen2.5-72B-Instruct'],
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    keyPlaceholder: 'sk-...',
    docs: 'https://cloud.siliconflow.cn/',
  },

  // ===== MAJOR PLATFORMS =====
  'mistral': {
    id: 'mistral',
    name: 'Mistral AI',
    icon: '🌀',
    category: 'Major Platforms',
    models: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'open-mixtral-8x22b'],
    defaultModel: 'mistral-large-latest',
    keyPlaceholder: 'API Key',
    docs: 'https://console.mistral.ai/',
  },
  'cohere': {
    id: 'cohere',
    name: 'Cohere',
    icon: '🔴',
    category: 'Major Platforms',
    models: ['command-r-plus', 'command-r', 'command'],
    defaultModel: 'command-r-plus',
    keyPlaceholder: 'API Key',
    docs: 'https://dashboard.cohere.com/',
  },
  'groq': {
    id: 'groq',
    name: 'Groq',
    icon: '⚡',
    category: 'Major Platforms',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
    defaultModel: 'llama-3.3-70b-versatile',
    keyPlaceholder: 'gsk_...',
    docs: 'https://console.groq.com/',
  },
  'xai': {
    id: 'xai',
    name: 'xAI (Grok)',
    icon: '🦅',
    category: 'Major Platforms',
    models: ['grok-beta', 'grok-2-1212', 'grok-2-vision-1212'],
    defaultModel: 'grok-beta',
    keyPlaceholder: 'xai-...',
    docs: 'https://console.x.ai/',
    supportsVision: true,
  },
  'perplexity': {
    id: 'perplexity',
    name: 'Perplexity AI',
    icon: '🔍',
    category: 'Major Platforms',
    models: ['llama-3.1-sonar-large-128k-online', 'llama-3.1-sonar-small-128k-online'],
    defaultModel: 'llama-3.1-sonar-large-128k-online',
    keyPlaceholder: 'pplx-...',
    docs: 'https://www.perplexity.ai/settings/api',
  },

  // ===== CLOUD GPU / INFERENCE =====
  'together': {
    id: 'together',
    name: 'Together AI',
    icon: '🤝',
    category: 'Cloud GPU',
    models: ['meta-llama/Llama-3.3-70B-Instruct-Turbo', 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo'],
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    keyPlaceholder: 'API Key',
    docs: 'https://api.together.xyz/',
  },
  'fireworks': {
    id: 'fireworks',
    name: 'Fireworks AI',
    icon: '🎆',
    category: 'Cloud GPU',
    models: ['accounts/fireworks/models/llama-v3p3-70b-instruct', 'accounts/fireworks/models/qwen2p5-72b-instruct'],
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    keyPlaceholder: 'API Key',
    docs: 'https://fireworks.ai/',
  },
  'replicate': {
    id: 'replicate',
    name: 'Replicate',
    icon: '🔄',
    category: 'Cloud GPU',
    models: ['meta/llama-3.3-70b-instruct', 'meta/llama-3.1-405b-instruct'],
    defaultModel: 'meta/llama-3.3-70b-instruct',
    keyPlaceholder: 'r8_...',
    docs: 'https://replicate.com/',
  },
  'huggingface': {
    id: 'huggingface',
    name: 'Hugging Face',
    icon: '🤗',
    category: 'Cloud GPU',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    keyPlaceholder: 'hf_...',
    docs: 'https://huggingface.co/settings/tokens',
  },
  'hyperbolic': {
    id: 'hyperbolic',
    name: 'Hyperbolic',
    icon: '🌀',
    category: 'Cloud GPU',
    models: ['meta-llama/Meta-Llama-3.1-405B-Instruct', 'meta-llama/Meta-Llama-3.1-70B-Instruct'],
    defaultModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    keyPlaceholder: 'API Key',
    docs: 'https://app.hyperbolic.xyz/',
  },
  'novita': {
    id: 'novita',
    name: 'Novita AI',
    icon: '✨',
    category: 'Cloud GPU',
    models: ['deepseek/deepseek-v3', 'meta-llama/llama-3.3-70b-instruct'],
    defaultModel: 'deepseek/deepseek-v3',
    keyPlaceholder: 'API Key',
    docs: 'https://novita.ai/',
  },
  'deepinfra': {
    id: 'deepinfra',
    name: 'DeepInfra',
    icon: '🔬',
    category: 'Cloud GPU',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'mistralai/Mixtral-8x22B-Instruct-v0.1'],
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    keyPlaceholder: 'API Key',
    docs: 'https://deepinfra.com/',
  },
  'fal': {
    id: 'fal',
    name: 'Fal AI',
    icon: '🎯',
    category: 'Cloud GPU',
    models: ['fal-ai/llama-3.3-70b-instruct', 'fal-ai/flux/dev'],
    defaultModel: 'fal-ai/llama-3.3-70b-instruct',
    keyPlaceholder: 'API Key',
    docs: 'https://fal.ai/',
  },
  'runpod': {
    id: 'runpod',
    name: 'RunPod',
    icon: '🏃',
    category: 'Cloud GPU',
    models: ['custom-endpoint'],
    defaultModel: 'custom-endpoint',
    keyPlaceholder: 'API Key',
    docs: 'https://www.runpod.io/',
  },
  'lambda': {
    id: 'lambda',
    name: 'Lambda Labs',
    icon: 'λ',
    category: 'Cloud GPU',
    models: ['llama3.1-405b', 'llama3.1-70b', 'llama3.1-8b'],
    defaultModel: 'llama3.1-70b',
    keyPlaceholder: 'API Key',
    docs: 'https://cloud.lambdalabs.com/',
  },

  // ===== CLOUD PROVIDERS =====
  'azure': {
    id: 'azure',
    name: 'Azure OpenAI',
    icon: '☁️',
    category: 'Cloud Providers',
    models: ['gpt-4o', 'gpt-4-turbo', 'gpt-35-turbo'],
    defaultModel: 'gpt-4o',
    keyPlaceholder: 'API Key',
    docs: 'https://portal.azure.com/',
  },
  'aws': {
    id: 'aws',
    name: 'AWS Bedrock',
    icon: '🟠',
    category: 'Cloud Providers',
    models: ['anthropic.claude-3-5-sonnet', 'anthropic.claude-3-opus', 'meta.llama3-70b-instruct'],
    defaultModel: 'anthropic.claude-3-5-sonnet',
    keyPlaceholder: 'Access Key ID',
    docs: 'https://aws.amazon.com/bedrock/',
  },
  'vertex': {
    id: 'vertex',
    name: 'Google Vertex AI',
    icon: '🔷',
    category: 'Cloud Providers',
    models: ['gemini-1.5-pro', 'gemini-1.5-flash', 'claude-3-sonnet'],
    defaultModel: 'gemini-1.5-pro',
    keyPlaceholder: 'OAuth Token',
    docs: 'https://cloud.google.com/vertex-ai',
  },
  'cloudflare': {
    id: 'cloudflare',
    name: 'Cloudflare Workers AI',
    icon: '🟠',
    category: 'Cloud Providers',
    models: ['@cf/meta/llama-3.3-70b-instruct-fp8-fast', '@cf/meta/llama-3.1-8b-instruct'],
    defaultModel: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    keyPlaceholder: 'API Token',
    docs: 'https://dash.cloudflare.com/',
  },
  'databricks': {
    id: 'databricks',
    name: 'Databricks',
    icon: '🧱',
    category: 'Cloud Providers',
    models: ['databricks-dbrx-instruct', 'databricks-mixtral-8x7b-instruct'],
    defaultModel: 'databricks-dbrx-instruct',
    keyPlaceholder: 'dapi...',
    docs: 'https://databricks.com/',
  },
  'nvidia': {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    icon: '💚',
    category: 'Cloud Providers',
    models: ['meta/llama-3.3-70b-instruct', 'meta/llama-3.1-405b-instruct'],
    defaultModel: 'meta/llama-3.3-70b-instruct',
    keyPlaceholder: 'nvapi-...',
    docs: 'https://build.nvidia.com/',
  },

  // ===== SPECIALIZED PROVIDERS =====
  'stability': {
    id: 'stability',
    name: 'Stability AI',
    icon: '🎨',
    category: 'Specialized',
    models: ['stable-diffusion-xl-1024-v1-0', 'stable-image-ultra', 'stable-diffusion-3-large'],
    defaultModel: 'stable-diffusion-3-large',
    keyPlaceholder: 'sk-...',
    docs: 'https://platform.stability.ai/',
  },
  'elevenlabs': {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    icon: '🔊',
    category: 'Specialized',
    models: ['eleven_multilingual_v2', 'eleven_monolingual_v1', 'eleven_turbo_v2'],
    defaultModel: 'eleven_multilingual_v2',
    keyPlaceholder: 'API Key',
    docs: 'https://elevenlabs.io/',
    supportsAudio: true,
  },
  'voyage': {
    id: 'voyage',
    name: 'Voyage AI',
    icon: '🧭',
    category: 'Specialized',
    models: ['voyage-3', 'voyage-3-lite', 'voyage-2'],
    defaultModel: 'voyage-3',
    keyPlaceholder: 'API Key',
    docs: 'https://www.voyageai.com/',
  },
  'jina': {
    id: 'jina',
    name: 'Jina AI',
    icon: '🔗',
    category: 'Specialized',
    models: ['jina-embeddings-v3', 'jina-embeddings-v2-base-en'],
    defaultModel: 'jina-embeddings-v3',
    keyPlaceholder: 'API Key',
    docs: 'https://jina.ai/',
  },

  // ===== LOCAL / OPEN SOURCE =====
  'ollama': {
    id: 'ollama',
    name: 'Ollama (Local)',
    icon: '🦙',
    category: 'Local / Open',
    models: ['llama3.3', 'llama3.2', 'mistral', 'qwen2.5', 'deepseek-r1'],
    defaultModel: 'llama3.3',
    keyPlaceholder: 'No key required',
    docs: 'https://ollama.ai/',
    local: true,
  },
  'vllm': {
    id: 'vllm',
    name: 'vLLM',
    icon: '🚀',
    category: 'Local / Open',
    models: ['local-model'],
    defaultModel: 'local-model',
    keyPlaceholder: 'No key required',
    docs: 'https://vllm.ai/',
    local: true,
  },
  'localai': {
    id: 'localai',
    name: 'LocalAI',
    icon: '🏠',
    category: 'Local / Open',
    models: ['local-model'],
    defaultModel: 'local-model',
    keyPlaceholder: 'No key required',
    docs: 'https://localai.io/',
    local: true,
  },

  // ===== ENTERPRISE =====
  'anyscale': {
    id: 'anyscale',
    name: 'Anyscale',
    icon: '📊',
    category: 'Enterprise',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    keyPlaceholder: 'API Key',
    docs: 'https://www.anyscale.com/',
  },
  'sambanova': {
    id: 'sambanova',
    name: 'SambaNova',
    icon: '🔄',
    category: 'Enterprise',
    models: ['Meta-Llama-3.1-405B-Instruct', 'Meta-Llama-3.1-70B-Instruct'],
    defaultModel: 'Meta-Llama-3.1-70B-Instruct',
    keyPlaceholder: 'API Key',
    docs: 'https://sambanova.ai/',
  },
  'cerebras': {
    id: 'cerebras',
    name: 'Cerebras',
    icon: '🧠',
    category: 'Enterprise',
    models: ['llama3.1-8b', 'llama3.1-70b'],
    defaultModel: 'llama3.1-70b',
    keyPlaceholder: 'API Key',
    docs: 'https://cerebras.ai/',
  },

  // ===== API AGGREGATORS =====
  'openrouter': {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: '🔀',
    category: 'Aggregators',
    models: ['openai/gpt-4o', 'anthropic/claude-3.5-sonnet', 'google/gemini-pro-1.5', 'meta-llama/llama-3.3-70b-instruct'],
    defaultModel: 'openai/gpt-4o',
    keyPlaceholder: 'sk-or-...',
    docs: 'https://openrouter.ai/',
  },

  // ===== CUSTOM =====
  'custom': {
    id: 'custom',
    name: 'Custom Endpoint',
    icon: '⚙️',
    category: 'Custom',
    models: ['custom-model'],
    defaultModel: 'custom-model',
    keyPlaceholder: 'API Key (optional)',
    docs: '',
  },
};

export function getProvidersByCategory(): Record<string, AIProvider[]> {
  const categories: Record<string, AIProvider[]> = {};
  for (const provider of Object.values(AI_PROVIDERS)) {
    if (!categories[provider.category]) {
      categories[provider.category] = [];
    }
    categories[provider.category].push(provider);
  }
  return categories;
}

export function getProvider(id: string): AIProvider | undefined {
  return AI_PROVIDERS[id];
}

export const PROVIDER_COUNT = Object.keys(AI_PROVIDERS).length;
